#!/usr/bin/env bash
set -Eeuo pipefail

BIN_FILE_PATH=$(readlink -f $0)
LIB_PATH="$(dirname $BIN_FILE_PATH)"
CWD_PATH="$PWD"

HOST_SCRIPTS_PATH="${LIB_PATH}/scripts/host/"
CONTAINER_SCRIPTS_PATH="${LIB_PATH}/scripts/container/"
LIB_SCRIPTS_PATH="${LIB_PATH}/scripts/lib/"

export LIB_PATH="${LIB_PATH}" 
export CWD_PATH="${CWD_PATH}" 
export CAESAR_VERSION=$(npm run version --silent)

"${LIB_SCRIPTS_PATH}/command-proxy" "$@"