#!/usr/bin/env node
const fs = require('fs');
const { exit } = require('process');

const file = process.argv[2];

const key = process.argv[3];

const value = process.argv[4];

let content = `${key}=${value}`

if (fs.existsSync(file)) {

  try {
    
    content += "\n" + fs.readFileSync(file).toString().replace(new RegExp(`${ key }=(.*)`, 'g'), '');

    fs.writeFileSync(file, content.replace(/^\s*\n/gm, ''));

  } catch {

    // File is a folder, skip.

  }

}
