#!/usr/bin/env node
const fs = require('fs');

const file = process.argv[2];

const key = process.argv[3];

const value = process.argv[4];

const content = `${ key }=${ value }
` + fs.readFileSync(file).toString().replace(new RegExp(`${ key }=(.*)`, 'g'), '');

fs.writeFileSync(file, content.replace(/^\s*\n/gm, ''));