#!/usr/bin/env node
const _ = require('lodash');

const domainList = process.argv[2].split(',');

const result = _.reduce(domainList, function (list, item, index) {

  item = `https://${ item }`;
  
  if (index === 0) {

    return item;

  } else if (index === 1) {
    
    return `${ list },${ item }`;

  } // end if;

  const glue = index % 2 ? ',' : "\n";

  return list + `${ glue }${ item }`;

}, "");

console.log(result);
