#!/usr/bin/env node
const fs = require('fs');
const { exit } = require('process');
const slugify = require('slugify');

const hostsContent = fs.readFileSync('/etc/hosts');

const domain = process.argv[2];

if (!domain) {

  exit(1)

}

let slug = slugify(process.argv[2], {
  replacement: '-',  // replace spaces with replacement character, defaults to `-`
  // remove: /\.([a-z])+/, // remove characters that match regex, defaults to `undefined`
  lower: true,      // convert to lower case, defaults to `false`
});

slug = slug.replace(/\./g, '-');

const additional = process.argv[4] ?? '';

const mapped = process.argv[3] ?? '';

const domainList = [
  domain, 
  ...(additional ? additional.split(',') : []),
  ...(mapped ? mapped.split(',') : []),
];

let finalList = '';

for (let i = 0; i < domainList.length; i++) {
  
  const item = domainList[i];

  finalList += `\n127.0.0.1 ${ item }`.padEnd(40) + `# Caesar - ${ slug }`
  
} // end for;

const ceasarBlock = finalList;

const regexp = new RegExp("\\s(.+)(#\\s(Caesar - " + slug + "))", 'g');

const newContent = hostsContent.toString().replace(regexp, '') + ceasarBlock;

fs.writeFileSync('/etc/hosts', newContent);
