#!/usr/bin/env bash

. ${LIB_PATH}/scripts/lib/func.sh

# Name of the project.
NAME=$1

DOMAIN_NAME=$2

mkdir "$NAME" 2> /dev/null

if [ $? -eq 1 ]; then

  pdns "Unable to create the target directory '$1'..."

  echo ""

  exit 1;

fi

cd "$NAME";

npm init -y > /dev/null 2>&1

npm link caesar > /dev/null 2>&1

caesar up $DOMAIN_NAME

pdns "Run \`cd $NAME\` to change to the newly created project"
pdns "Or run \`code $NAME\` to open it on VSCode."

echo ""
