#!/usr/bin/env bash
# set -x

. ${LIB_PATH}/scripts/lib/func.sh

if [ -n "$1" ]; then
  SLUG=$1
else
  . "${CWD_PATH}/.env" > /dev/null 2>&1
fi

if [ "$SLUG" != "shutdown" ]; then

  start_spinner "Shutting containers for site $SLUG down..."
    
  docker container stop $(docker container ls -q --all --filter "name=$SLUG") > /dev/null 2>&1
  docker container kill $(docker container ls -q --all --filter "name=$SLUG") > /dev/null 2>&1
  docker container rm $(docker container ls -q --all --filter "name=$SLUG") > /dev/null 2>&1

  stop_spinner 0
  
  pd "See you later!"

else

  start_spinner "Shutting containers for all sites..."

  docker container stop $(docker container ls -q --all) > /dev/null 2>&1
  docker container kill $(docker container ls -q --all) > /dev/null 2>&1
  docker container rm $(docker container ls -q --all) > /dev/null 2>&1

  stop_spinner 0
  
  pd "See you later!"

fi

echo ""